name: perfect_freehand
version: 2.0.1
description: Draw perfect pressure-sensitive freehand lines. A set of functions for turning input points into a polygon of outline points.
homepage: https://github.com/steveruizok/perfect-freehand-dart
repository: https://github.com/steveruizok/perfect-freehand-dart
documentation: https://github.com/steveruizok/perfect-freehand-dart
issue_tracker: https://github.com/steveruizok/perfect-freehand-dart/issues
environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
